package com.yaps.petstore.service;

import com.yaps.petstore.domain.category.CategoryDAO;
import com.yaps.petstore.domain.customer.Customer;
import com.yaps.petstore.domain.customer.CustomerDAO;
import com.yaps.petstore.domain.item.ItemDAO;
import com.yaps.petstore.domain.order.Order;
import com.yaps.petstore.domain.order.OrderDAO;
import com.yaps.petstore.domain.orderline.OrderLine;
import com.yaps.petstore.domain.orderline.OrderLineDAO;
import com.yaps.petstore.domain.product.ProductDAO;
import com.yaps.petstore.exception.*;

import java.util.Collection;
import java.util.Iterator;

/**
 * This class is a facade for all order services.
 */
public final class OrderService {
    private static final CustomerDAO _customerDAO = new CustomerDAO();
    private static final OrderDAO _orderDAO = new OrderDAO();
    private static final OrderLineDAO _orderLineDAO = new OrderLineDAO();

    // ======================================
    // =           Business methods         =
    // ======================================
    /**
     * Given a Order object, this method creates a Order.
     *
     * @param order cannot be null.
     * @return the created Order
     * @throws CreateException is thrown if a DomainException is caught
     *                         or a system failure is occurs
     * @throws CheckException  is thrown if a invalid data is found
     */
    public Order createOrder(final Order order) throws CreateException, CheckException {
        if (order == null)
            throw new CreateException("Order object is null");

        if (order.getCustomer() == null)
            throw new CheckException("Invalid Customer");

        if (order.getOrderLines() == null || order.getOrderLines().size() < 0)
            throw new CheckException("There are no order lines");

        // Finds the customer
        try {
            _customerDAO.findByPrimaryKey(order.getCustomer().getId());
        } catch (FinderException e) {
            throw new CreateException("Customer must exist to create an order");
        }

        // Creates the object
        _orderDAO.insert(order);

        // Creates all the orderLines linked with the order
        for (Iterator iterator = order.getOrderLines().iterator(); iterator.hasNext();) {
            final OrderLine orderLine = (OrderLine) iterator.next();
            orderLine.setOrder(order);
            _orderLineDAO.insert(orderLine);
        }

        return order;
    }

    /**
     * Given an id this method uses the Order domain object to load all the data of this
     * object.
     *
     * @param orderId identifier
     * @return Order
     * @throws ObjectNotFoundException is thrown if no object with this given id is found
     * @throws FinderException         is thrown if a DomainException is caught
     *                                 or a system failure is occurs
     * @throws CheckException          is thrown if a invalid data is found
     */
    public Order findOrder(final String orderId) throws FinderException, CheckException {
        // Finds the object
        final Order order = (Order) _orderDAO.findByPrimaryKey(orderId);

        // Retreives the data for the customer and sets it
        Customer customer = (Customer) _customerDAO.findByPrimaryKey(order.getCustomer().getId());
        order.setCustomer(customer);

        // Retreives the data for all the order lines
        final Collection orderLines = _orderLineDAO.findAll(orderId);
        order.setOrderLines(orderLines);

        return order;
    }

    /**
     * Given an id, this method finds an Order domain object and then calls its deletion
     * method.
     *
     * @param orderId identifier
     * @throws RemoveException is thrown if a DomainException is caught
     *                         or a system failure is occurs
     * @throws CheckException  is thrown if a invalid data is found
     */
    public void deleteOrder(final String orderId) throws RemoveException, CheckException {
        final Order order = new Order();

        // Checks if the object exists
        try {
            _orderDAO.findByPrimaryKey(orderId);
        } catch (FinderException e) {
            throw new RemoveException("Order must exist to be deleted");
        }

        // Deletes the object
        // Deletes the object
        try {
        	_orderDAO.remove(orderId);
        } catch (ObjectNotFoundException e) {
            throw new RemoveException("Customer must exist to be deleted");
        }
    }

    /**
     * This method returns a unique identifer generated by the system. 
     *
     * @param domainClassName name of a domain class (Order, OrderLine, ...)
     * @return a unique identifer
     */
    public final String getUniqueId(final String domainClassName) {
        return _orderDAO.getUniqueId(domainClassName);
    }
}
