package com.yaps.petstore.server.service.catalog;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

import com.yaps.petstore.common.dto.CustomerDTO;
import com.yaps.petstore.common.exception.CheckException;
import com.yaps.petstore.common.exception.CreateException;
import com.yaps.petstore.common.exception.FinderException;
import com.yaps.petstore.common.exception.ObjectNotFoundException;
import com.yaps.petstore.common.exception.RemoveException;
import com.yaps.petstore.common.exception.UpdateException;
import com.yaps.petstore.common.logging.Trace;
import com.yaps.petstore.server.domain.customer.Customer;
import com.yaps.petstore.server.domain.customer.CustomerDAO;
import com.yaps.petstore.server.service.AbstractRemoteService;
import com.yaps.petstore.server.service.customer.CustomerServiceRemote;

public class CatalogService extends AbstractRemoteService implements CatalogServiceRemote{

    // ======================================
    // =             Attributes             =
    // ======================================
//    private static final CustomerDAO _dao = new CustomerDAO();

    // ======================================
    // =            Constructors            =
    // ======================================
    public CatalogService() throws RemoteException {
    }

    // ======================================
    // =           Business methods         =
    // ======================================
   
    
    
    /**
     * This method returns a unique identifer generated by the system. 
     *
     * @return a unique identifer
     */
    public final String getUniqueId() {
        return _dao.getUniqueId();
    }

}
